### ISSUE TITLE
Enncoders  not compatible with sklearn pipelines now

### ISSUE THREAD

**Issue by nassimtaleb** [scikit-learn-contrib/category_encoders#265] opened 2020-08-11 19:32 UTC
Hi, while lookin at the code I realized that the encoders use the variable 'y' to pass information when transforming to use the 'train' behaviour or 'test' behaviour . This does not seem correct since when calling fit_transform on a sklearn pipeline, it first calls fit and then transform without the 'y' parameter. https://github.com/scikit-learn/scikit-learn/blob/0fb307bf39bbdacd6ed713c00724f8f871d60370/sklearn/pipeline.py#L742

An easy fix would be to directly define fit_transform and use 'y' there to get 'train' behaviour. And include only 'test' behaviour in the transform.

**Comment by janmotl** [comment] 2020-08-11 19:49
Which encoders are we talking about?

**Comment by nassimtaleb** [comment] 2020-08-26 23:23
Leavoneout for sure, but I think all of them have the same issue. The only way put is by calling cvwrapper, which does apply fit-transform

**Comment by Rcubes** [comment] 2020-09-26 23:02
Are there any updates on this? I have no experience solving issues but if there is any way to contribute to solve this issue? I'm having a hard time dealing with pipelines combined with TargetEncoder() and I would like to get this fixed.

Any guidelines will be deeply appreciated

**Comment by janmotl** [comment] 2020-09-27 13:03
Transform method in LeaveOneOut is supposed to behave differently on training data and testing data. And it is known that it causes issues with sklearn pipelines. Nevertheless, unsupervised encoders can behave like any other encoder in sklearn. And possibly some supervised encoders can behave like that as well (I do not know which one, if any). 

What can be done to make the situation better: 
1. Improve the documentation (e.g.: explicitly mark encoders that violate sklearn's expectations and mention possible workarounds). 
2. Write unit tests to ensure that encoders, which should work with sklearn pipelines, actually work (and will continue to work) with sklearn pipelines.
3. If you modify the encoders, perform tests on real data to make sure that the generalization ability of the downstream classifiers/regressors does not degrade (e.g.: look in `examples/benchmarking_large`). One of the big issues of supervised encoders is that it may cause sever overfitting of the downstream models.

For contributing, check `CONTRIBUTING.md`. The issue is important and should not be left unfixed. However, I am not active in the project anymore. See #248.

**Comment by PaulWestenthanner** [comment] 2022-06-02 11:29
closing as by suggestion of @bmreiniger

**Closed by PaulWestenthanner** 2022-06-02 11:29 UTC
