### ISSUE TITLE
Add Unary/ Thermometer Encoding

### ISSUE THREAD

**Issue by iki77** [scikit-learn-contrib/category_encoders#299] opened 2021-05-19 13:57 UTC
Add Unary/Thermometer Encoding as an alternative for Ordinal Encoding.
According to [Source](https://openreview.net/forum?id=S18Su--CW) it is also more robust to adversarial examples

**Comment by GLevV** [comment] 2022-02-13 09:13
This is an alternative to one hot encoding, not ordinal. But it could be interesting and should be relatively easy to do

**Comment by GLevV** [comment] 2022-02-14 08:52
I think it could be added as a parameter to existing OHE implementation

**Comment by PaulWestenthanner** [comment] 2023-01-05 23:16
I've finally worked on this. This issue is a duplicate of #199 anyway right?

**Comment by PaulWestenthanner** [comment] 2023-01-14 20:02
added in #222

**Closed by PaulWestenthanner** 2023-01-14 20:02 UTC
Labels: enhancement
