### ISSUE TITLE
HashingEncoder doesn't transform the data

### ISSUE THREAD

**Issue by xKHUNx** [scikit-learn-contrib/category_encoders#215] opened 2019-10-09 10:22 UTC
I'm trying to see the output of using HashingEncoder, and I've used the original sample code from the documentation, and I don't see any differences between the transformed and non-transformed dataframe. I suspect the columns are treated as numerical features, so I've added my own categorical column (US state code) and try to transform it.

Yet again, the output is same as the input. I've even tried using pipeline, and it seems to run normally (as if the categorical column is converted to numerical ones).

So I'm wondering why is the transformed dataframe is not changed? I'm expecting some one-hot-encoded columns with binary values. If it doesn't work, why it works in the pipeline? 

*Pipeline code not included.

Here is the code.
```
from category_encoders.hashing import HashingEncoder
import numpy as np
import pandas as pd
from sklearn.datasets import load_boston
bunch = load_boston()
y = bunch.target
X = pd.DataFrame(bunch.data, columns=bunch.feature_names)
cardinals = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DC", "DE", "FL", "GA", 
          "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", 
          "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", 
          "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", 
          "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"]

X['cat'] = np.random.choice(cardinals, X.shape[0])

enc = HashingEncoder(cols=['cat']).fit(X, y)
enc.fit(X, y)
numeric_dataset = enc.transform(X)
print(numeric_dataset.info())
```

**Comment by janmotl** [comment] 2019-10-09 12:22
This is interesting. When I run the above code, I am getting:
```
RangeIndex: 506 entries, 0 to 505
Data columns (total 21 columns):
col_0      506 non-null int64
col_1      506 non-null int64
col_2      506 non-null int64
col_3      506 non-null int64
col_4      506 non-null int64
col_5      506 non-null int64
col_6      506 non-null int64
col_7      506 non-null int64
CRIM       506 non-null float64
ZN         506 non-null float64
INDUS      506 non-null float64
CHAS       506 non-null float64
NOX        506 non-null float64
RM         506 non-null float64
AGE        506 non-null float64
DIS        506 non-null float64
RAD        506 non-null float64
TAX        506 non-null float64
PTRATIO    506 non-null float64
B          506 non-null float64
LSTAT      506 non-null float64
dtypes: float64(13), int64(8)
memory usage: 83.1 KB
```
The `cat` column is converted into `col_` columns as expected.

Which version of categorical-encoding, pandas and python do you use? Does the issue replicate when you upgrade/downgrade categorical-encoding package?

**Comment by xKHUNx** [comment] 2019-10-10 02:06
I'm unable to find the version history to try upgrade and downgrading this package. But here's all my relevant package versions:

```
Package              Version 
-------------------- --------------       
category-encoders    2.1.0          
numpy                1.17.2         
pandas               0.25.1         
scipy                1.3.1     
```

My Python version:
`Python 3.7.4`

**Comment by janmotl** [comment] 2019-10-10 09:18
I use the same versions as you.

If you are using pip, then it should be possible to downgrade with:
`
pip install category_encoders==2.0.0
`

If downgrade does not help: Clone the repository from Github and execute all tests in category_encoders/tests. If HashingEncoder doesn't encode categorical columns, `test_classification` in `test_encoders.py` should fail. But if more tests fail, it could be interesting to see which one.

As an evidence that at least sometimes the test passes see:
https://travis-ci.org/scikit-learn-contrib/categorical-encoding/builds/592098517

**Comment by xKHUNx** [comment] 2019-10-10 10:23
Downgrading to using `category_encoders==2.0.0` works for me. Should I close this issue?

**Comment by xKHUNx** [comment] 2019-10-11 02:48
Upgraded back to `category_encoders==2.1.0` 

`print(multiprocessing.cpu_count())` returns 12, which is expected behaviour as I have a 12 core CPU.

For these cases:
`enc = HashingEncoder(cols=['cat']).fit(X, y)` 
`enc = HashingEncoder(cols=['cat'], max_process=2).fit(X, y)`
`enc = HashingEncoder(cols=['cat'], max_process=3).fit(X, y)`

The output is:
```
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
CRIM       506 non-null float64
ZN         506 non-null float64
INDUS      506 non-null float64
CHAS       506 non-null float64
NOX        506 non-null float64
RM         506 non-null float64
AGE        506 non-null float64
DIS        506 non-null float64
RAD        506 non-null float64
TAX        506 non-null float64
PTRATIO    506 non-null float64
B          506 non-null float64
LSTAT      506 non-null float64
cat        506 non-null object
dtypes: float64(13), object(1)
memory usage: 55.5+ KB
None
```

Only when `max_process=1`, ie:
`enc = HashingEncoder(cols=['cat'], max_process=1).fit(X, y)`

the output is correct:
```
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 21 columns):
col_0      506 non-null int64
col_1      506 non-null int64
col_2      506 non-null int64
col_3      506 non-null int64
col_4      506 non-null int64
col_5      506 non-null int64
col_6      506 non-null int64
col_7      506 non-null int64
CRIM       506 non-null float64
ZN         506 non-null float64
INDUS      506 non-null float64
CHAS       506 non-null float64
NOX        506 non-null float64
RM         506 non-null float64
AGE        506 non-null float64
DIS        506 non-null float64
RAD        506 non-null float64
TAX        506 non-null float64
PTRATIO    506 non-null float64
B          506 non-null float64
LSTAT      506 non-null float64
dtypes: float64(13), int64(8)
memory usage: 83.1 KB
None
```

**Comment by janmotl** [comment] 2019-10-11 12:47
@SLLiu96 Can you help investigate the issue?

**Comment by SLLiu96** [comment] 2019-10-11 12:54
@janmotl @xKHUNx 

I'm sorry this happened, it might be caused by the data concat, I'm working on it.

**Comment by janmotl** [comment] 2019-10-11 12:55
@SLLiu96 Thank you.

**Comment by SLLiu96** [comment] 2019-10-11 13:38
@janmotl @xKHUNx 

Hi! I found that the code running here performance just as the expected, I got this output below:

`
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 21 columns):
col_0      506 non-null int64
col_1      506 non-null int64
col_2      506 non-null int64
col_3      506 non-null int64
col_4      506 non-null int64
col_5      506 non-null int64
col_6      506 non-null int64
col_7      506 non-null int64
CRIM       506 non-null float64
ZN         506 non-null float64
INDUS      506 non-null float64
CHAS       506 non-null float64
NOX        506 non-null float64
RM         506 non-null float64
AGE        506 non-null float64
DIS        506 non-null float64
RAD        506 non-null float64
TAX        506 non-null float64
PTRATIO    506 non-null float64
B          506 non-null float64
LSTAT      506 non-null float64
dtypes: float64(13), int64(8)
memory usage: 83.1 KB
None
``

Package versions are the same as @xKHUNx , and I downgraded category_encoders to 2.0.0 and back to 2.1.0

yet also tried ``enc = HashingEncoder(cols=['cat'], max_process=1).fit(X, y)``, ``enc = HashingEncoder(cols=['cat'], max_process=2).fit(X, y)``, ...... ``enc = HashingEncoder(cols=['cat'], max_process=12).fit(X, y)``

still output the same.

@xKHUNx Could you please re-download the category_encoders and try it again? I'm making some tests that may avoid this happened.

**Comment by SLLiu96** [comment] 2019-10-11 13:56
Here I reran the demo with encoding each columns, 2 columns, ......, even all the columns, all of them output the expected. I'm now wondering is this issue related with system platform? like multiprocessing between linux/macos and win?

**Comment by xKHUNx** [comment] 2019-10-14 02:30
@SLLiu96 
Reinstalled category encoder with `category_encoders==2.1.0` .

Now fitting the encoder with anything other than with `max_process=1`
i.e. enc = `HashingEncoder(cols=['cat'], max_process=1).fit(X, y)` and I will get this error.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<my directory>\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "<my directory>\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: 'HashingEncoder' object has no attribute '__require_data'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<my directory>\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "<my directory>\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: 'HashingEncoder' object has no attribute '__require_data'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File <my directory>\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "<my directory>\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: 'HashingEncoder' object has no attribute '__require_data'
```
BTW, I'm using a PC with Windows 10 Home Single Language.

**Comment by SLLiu96** [comment] 2019-10-14 02:44
@xKHUNx 
Does this error still appear when using max_process(>1) or without this parameter?

This is strange that everything goes well in my laptop either in win10 or mac.

This error seems the HashingEncoder doesn't contain the multi-processing, could you please ctrl + click the HashingEncoder and see if there are parameters 'max_process' and 'max_sample' in the construct function?

**Comment by xKHUNx** [comment] 2019-10-14 03:05
@SLLiu96 

Using Jupyter Notebook shift + tab, I get this from the import statement:
![image](https://user-images.githubusercontent.com/10325191/66727445-d859f500-ee71-11e9-9dce-8044ea9aae2a.png)

> Does this error still appear when using max_process(>1) or without this parameter?
No, only `enc = HashingEncoder(cols=['cat'], max_process=1).fit(X, y)` works.

I would like to add that the error message probably appears when I first reported this issue, but I overlooked it as the message only appears on the command prompt running the jupyter notebook, sometimes certain error only shows up there (I believed error messages from multithreaded programs are usually shows up there instead of in the cells).

> (May I ask you a private question that... are you from china?)
No, I'm Malaysian Chinese. Are you?

**Comment by SLLiu96** [comment] 2019-10-14 03:23
@xKHUNx 

I may consider that error shows up most probably in jupyter notebook, still be an issue if it does, and i'm trying again in jupyter notebook.

And yes, I'm from China, I thought maybe it's more efficient if using QQ or WeChat 2333.

**Comment by SLLiu96** [comment] 2019-10-14 03:45
![1](https://user-images.githubusercontent.com/38213534/66728466-b2cfea00-ee77-11e9-8fc3-863fd1d4f01e.jpg)
![2](https://user-images.githubusercontent.com/38213534/66728467-b2cfea00-ee77-11e9-9471-092b685281de.jpg)

Things getting weird now, still can't replicate it in jupyter. Tips: using parameter 'verbose=5' can output work detail of each process. Seems no error here.

**Comment by xKHUNx** [comment] 2019-10-14 05:54
I suspect the problem lies in this few line of codes in [here](https://github.com/scikit-learn-contrib/categorical-encoding/blob/master/category_encoders/hashing.py).
![image](https://user-images.githubusercontent.com/10325191/66729526-93888b00-ee7e-11e9-90b1-6f5ef15c1bc4.png)

And based on the error I've posted earlier, it could be that the child process is trying to access the private methods (`__require_data`) of the parent process. Maybe it was the `multiprocessing` module we should look into?

Correct me if I'm wrong.

**Comment by SLLiu96** [comment] 2019-10-14 06:30
@xKHUNx 

The access to `__require_data` is fine, this only prevent from `enc = HashingEncoder` and then `enc.__require_data()`.

``multiprocessing `` is from python group, not much related with this issue.

Could you please set verbose=5 and replicate the error again, and if could, post all your code and output?

**Comment by xKHUNx** [comment] 2019-10-16 02:39
I've used the test case I've provided from the first issue. The result is the same as mentioned [here](https://github.com/scikit-learn-contrib/categorical-encoding/issues/215#issuecomment-540877429). But I will put here again for clarity.

Case #1 - **max_process** is set to 1.
```
from category_encoders.hashing import HashingEncoder
import numpy as np
import pandas as pd
from sklearn.datasets import load_boston
bunch = load_boston()
y = bunch.target
X = pd.DataFrame(bunch.data, columns=bunch.feature_names)
cardinals = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DC", "DE", "FL", "GA", 
          "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", 
          "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", 
          "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", 
          "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"]

X['cat'] = np.random.choice(cardinals, X.shape[0])

enc = HashingEncoder(cols=['cat'], max_process=1)
enc.fit(X, y)
numeric_dataset = enc.transform(X)
print(numeric_dataset.info())
```
Output:
```
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 21 columns):
col_0      506 non-null int64
col_1      506 non-null int64
col_2      506 non-null int64
col_3      506 non-null int64
col_4      506 non-null int64
col_5      506 non-null int64
col_6      506 non-null int64
col_7      506 non-null int64
CRIM       506 non-null float64
ZN         506 non-null float64
INDUS      506 non-null float64
CHAS       506 non-null float64
NOX        506 non-null float64
RM         506 non-null float64
AGE        506 non-null float64
DIS        506 non-null float64
RAD        506 non-null float64
TAX        506 non-null float64
PTRATIO    506 non-null float64
B          506 non-null float64
LSTAT      506 non-null float64
dtypes: float64(13), int64(8)
memory usage: 83.1 KB
None
```

Case #2 - **max_process** is set to any number other than 1, or not provided with a value.
```
from category_encoders.hashing import HashingEncoder
import numpy as np
import pandas as pd
from sklearn.datasets import load_boston
bunch = load_boston()
y = bunch.target
X = pd.DataFrame(bunch.data, columns=bunch.feature_names)
cardinals = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DC", "DE", "FL", "GA", 
          "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", 
          "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", 
          "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", 
          "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"]

X['cat'] = np.random.choice(cardinals, X.shape[0])

enc = HashingEncoder(cols=['cat'], max_process=2)
enc.fit(X, y)
numeric_dataset = enc.transform(X)
print(numeric_dataset.info())
```
Output:
```
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
CRIM       506 non-null float64
ZN         506 non-null float64
INDUS      506 non-null float64
CHAS       506 non-null float64
NOX        506 non-null float64
RM         506 non-null float64
AGE        506 non-null float64
DIS        506 non-null float64
RAD        506 non-null float64
TAX        506 non-null float64
PTRATIO    506 non-null float64
B          506 non-null float64
LSTAT      506 non-null float64
cat        506 non-null object
dtypes: float64(13), object(1)
memory usage: 55.5+ KB
None
```

**Comment by SLLiu96** [comment] 2019-10-16 08:45
@xKHUNx 

Doesn't ``verbose=5``  make any more output ?

**Comment by bruinAlex** [comment] 2019-10-23 20:14
Having the exact same issue running the example code on the boston dataset. Here's what I've tried so far based on the discussions above, and which seems to have the same results as the topic author. 

- OS : Win10
- cpu_count = 8
- Python: 3.7.0
- category-encoders: 2.1.0
- pandas: 0.25.1
- numpy: 1.17.2
- scipy: 1.3.1
- Not using Conda
- Running from inside virtualenv
- Downgrading to category-encoders 2.0.0 fixes the problem and results match the example
- max_process=1: this also fixes the problem in category-encoders 2.1.0.
- Jupyter vs non-Jupyter: issue occurs in command line script and in Jupyter

**Comment by SLLiu96** [comment] 2019-10-24 01:32
@bruinAlex 

Could you please use the parameter ``verbose=5`` and post your output here?

**Comment by SLLiu96** [comment] 2019-10-24 03:17
@xKHUNx @bruinAlex @janmotl 

FINALLY, I've located the error, it's been caused because in some case, multiprocessing can't call the private method ``__require_data()``, but this issue only occurs in Windows and without IDE.

It would be fixed soon, might be in this weekends. Once done I'll at you, and sorry about this issue, for temporary, downgrade category_encoders to 2.0.0 or use ``max_process=1`` .

**Comment by SLLiu96** [comment] 2019-10-24 10:05
@xKHUNx @bruinAlex @janmotl 

Bug fixed by turning ``__require_data()`` into static ``require_data``.

I've found an explanation of issues in windows from python.org [HERE](https://docs.python.org/2/library/multiprocessing.html?highlight=process#windows).

Also, as far as I know, Windows implements multiprocessing in a different way to linux/unix (WORSE supported in WIN). It brings ANOTHER ISSUE that transforming a small dataset with multiprocessing is SLOWER than single-processing **_( ONLY IN WINDOWS )_**.

In my test, time (second) of different ``max_process`` listed below:

(CPU is 2C4T, dataset contains 24 columns, encode 1 column)

| rows | time of max_process=1 | time of max_process=2 | time of max_proce=4 |
| :---: | :---: | :---: | :---: |
| 5k | 5.6719 | 7.2966 | 10.9216 |
| 10k | 9.4524 | 9.6240 | 11.3289 |
| 50k | 33.1552 | 22.1251 | 19.0312 |
| 100k | 60.8440 | 35.9365 | 28.2346 |

I suspect that's because multiprocesssing costs more CPU resource than the acceleration it can provide, anyway, this happends in linux/unix too but only on a really small dataset (less than 100 rows).

I'll pull a new PR after CI test.

**Comment by janmotl** [comment] 2019-10-24 10:14
@SLLiu96  We may consider setting `max_process=1` as the default value.

**Comment by SLLiu96** [comment] 2019-10-24 10:17
@janmotl 

OK. Maybe we should add an explanation in doc.

Should I PR now?

**Comment by janmotl** [comment] 2019-10-24 12:44
@SLLiu96 
> Maybe we could check the system, for windows set max_process=1 as default, and automatically for others. Is this all right?

I am OK with that. Document it and make the PR.

**Closed** 2023-01-21 21:21 UTC
