### ISSUE TITLE
CountEncoder not working?

### ISSUE THREAD

**Issue by JPFrancoia** [scikit-learn-contrib/category_encoders#237] opened 2020-03-06 16:52 UTC
Hi,

I'm having trouble getting the `CountEncoder` working. Calling `fit_transform` on an array-like structure doesn't seem to "do anything". Moreover the output seems slightly different compared to the output of a sklearn encoder. I think the API isn't fully compatible with sklearn, or it's a bug. Here is a snippet to reproduce the issue:

```python
import category_encoders as ce
import pandas as pd
from sklearn.datasets import load_boston

# prepare some data
bunch = load_boston()
X = pd.DataFrame(bunch.data, columns=bunch.feature_names)

enc = ce.CountEncoder()

enc.fit(X["RAD"])

output = enc.transform(X["RAD"])
```

Input (`X["RAD"]` before any transformation):

```
0      1.0
1      2.0
2      2.0
3      3.0
4      3.0
      ... 
501    1.0
502    1.0
503    1.0
504    1.0
505    1.0
Name: RAD, Length: 506, dtype: float64
```

Output:
```
     RAD
0    1.0
1    2.0
2    2.0
3    3.0
4    3.0
..   ...
501  1.0
502  1.0
503  1.0
504  1.0
505  1.0
```

Basically the output isn't what I expected. If I use a "normal" `LabelEncoder` from sklearn, here is what I get:

```
In [5]: le = LabelEncoder()                                                                                                                                                                   

In [6]: le.fit_transform(X["RAD"])                                                                                                                                                            
Out[6]: 
array([0, 1, 1, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 2, 4, 1, 4, 7, 7, 7, 7, 7, 7, 2, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 2, 2, 2, 2,
       1, 1, 1, 1, 3, 3, 3, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 0, 0, 3, 1, 1,
       1, 2, 2, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 5, 5, 5, 5,
       5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 2, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 0, 0, 0,
       0, 5, 5, 5, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 6, 6, 6, 6, 6, 6, 6,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3,
       3, 0, 0, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 4, 4, 2, 2, 3, 3, 0, 0, 3,
       3, 4, 3, 3, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
       8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
       8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
       8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
       8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
       8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
       8, 8, 8, 8, 3, 3, 3, 3, 3, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0])
```

However, if I run this:

```python
import category_encoders as ce
import pandas as pd
from sklearn.datasets import load_boston

# prepare some data
bunch = load_boston()
X = pd.DataFrame(bunch.data, columns=bunch.feature_names)

enc = ce.CountEncoder(cols=["RAD"]).fit(X["RAD"])

output = enc.transform(X["RAD"])
```

I get the expected output:

```
     RAD
0     20
1     24
2     24
3     38
4     38
..   ...
501   20
502   20
503   20
504   20
505   20

[506 rows x 1 columns]
```

Am I missing something here? FYI, in a tutorial on Kaggle [tuto](https://www.kaggle.com/matleonard/categorical-encodings), they show the sklearn-style syntax, but I don't think it would work if the current version of categorical-encoders (2.1.0, installed from pip).

**Comment by janmotl** [comment] 2020-03-07 09:30
Is the issue about:
> If the cols parameter isn't passed, all columns with object or pandas categorical data type will be encoded. 

? I.e.: That numerical columns are not by default converted? We use this behaviour because the library was designed to accept DataFrames with a mix of data types. And the data type can be used as a hint about "what are the categorical columns" (to avoid the need to repeatedly write something like `columns=X.select_dtypes('object')`.

Do you have a proposal how to deal with the "unexpected behaviour"?
- A change to the documentation?
- Raise a warning under some conditions?
- Change the behaviour of the encoders?

**Comment by JPFrancoia** [comment] 2020-03-07 15:55
Sorry I called it "unexpected behaviour", you guys seem to have thought about it.

> We use this behaviour because the library was designed to accept DataFrames with a mix of data types

So you mean the input to the `fit` method could be different from the input of the fit methods for `LabelEncoder`, `OneHotEncoder` or `OrdinalEncoder` ?
Because that's what surprised me with this module. If the input to the `fit` method should be the same, then I would expect the same behaviour.

However if we know the inputs can be different, then yes I think something should be done to clarify the behaviour since the encoders from these module work differently.

> If the cols parameter isn't passed, all columns with object or pandas categorical data type will be encoded.

That's fair. But let's look at this snippet:

```python
import category_encoders as ce
import pandas as pd
from sklearn.datasets import load_boston

# prepare some data
bunch = load_boston()
X = pd.DataFrame(bunch.data, columns=bunch.feature_names)

enc = ce.CountEncoder()

enc.fit(X["RAD"])

output = enc.transform(X["RAD"])
```

In this example, the `cols` parameter wasn't specified. When the `fit` method is called, it doesn't find any *columns with object or pandas categorical data type*. In this case I think a warning would help: "cols wasn't specified and no column of type object or categorical was found. Calling transform won't trigger any change".

What do you think?

**Comment by janmotl** [comment] 2020-03-07 17:11
> So you mean the input to the fit method could be different from the input of the fit methods for LabelEncoder, OneHotEncoder or OrdinalEncoder ?

The outputs of categorical-encoding and scikit can definitely be different. For example, the assigned values in OrdinalEncoder can be implementation specific (once it may follow the order of the _sorted unique values_, once it may follow the order of the _sorted hashes of the unique values_ and once it may follow the order in which the _values appeared in the input_).

> In this case I think a warning would help: "cols wasn't specified and no column of type object or categorical was found. Calling transform won't trigger any change".

OK. Will you make a pull request?

**Comment by JPFrancoia** [comment] 2020-03-07 17:20
> The outputs of categorical-encoding and scikit can definitely be different. For example, the assigned values in OrdinalEncoder can be implementation specific (in one implementation it may follow the order of the sorted unique values, in another it may follow the order in which the values appeared in the input).

You're talking about the output, what about the input?

> OK. Will you make a pull request?

No problem, give me a few days.

**Comment by janmotl** [comment] 2020-03-08 19:19
The inputs for `fit()` are different:
- sklearn: `fit(self, y)`
- categorical-encoding: `fit(self, X, y, **kwargs)`

because we support supervised encoders.

But there can be deviations that are without any reason. And such deviations should be reported.

**Comment by PaulWestenthanner** [comment] 2022-06-06 21:03
closing as the warning was added in #325

**Closed by PaulWestenthanner** 2022-06-06 21:03 UTC
